# Generated by Django 2.2 on 2020-10-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdtBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdtSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_subcategory_name', models.CharField(max_length=50)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CdtCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CdtVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_vendor', models.CharField(max_length=50)),
                ('nm_phone_number_vendor', models.CharField(max_length=10)),
                ('tx_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TdtColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_color', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TdtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_product_name', models.CharField(max_length=75)),
                ('tx_description', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('0', 'male'), ('1', 'female'), ('2', 'others')], max_length=2)),
                ('price_sale_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CdtBrand')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TdtColor')),
                ('id_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CdtSubcategory')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CdtVendor')),
            ],
        ),
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_size', models.CharField(max_length=4)),
                ('id_product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TdtProduct')),
            ],
        ),
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.CharField(max_length=150)),
                ('bl_primary', models.BooleanField(default=False)),
                ('id_product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TdtColor')),
            ],
        ),
    ]
