# Generated by Django 2.2 on 2020-10-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtsize',
            name='id_product_color',
        ),
        migrations.AddField(
            model_name='cdtsize',
            name='id_product_color',
            field=models.ManyToManyField(to='product.TdtProduct'),
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_color',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='product.TdtColor'),
        ),
    ]
