# Generated by Django 2.2 on 2020-10-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201026_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtproductphoto',
            name='tx_url_photo',
            field=models.ImageField(upload_to='img_products'),
        ),
    ]
