# Generated by Django 2.2 on 2020-10-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201026_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtproductphoto',
            name='id_product_color',
        ),
        migrations.AddField(
            model_name='tdtcolor',
            name='id_photo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.CdtProductPhoto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdtproductphoto',
            name='tx_url_photo',
            field=models.ImageField(null=True, upload_to='img_products'),
        ),
    ]
