# Generated by Django 2.2 on 2020-10-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201027_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtproductphoto',
            name='tx_url_photo',
            field=models.ImageField(upload_to='img_products'),
        ),
    ]
