# Generated by Django 2.2 on 2020-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201027_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtproductphoto',
            name='tx_url_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
